### ISSUE TITLE
Oculus Go Kernel - Does it work?

### ISSUE THREAD

**Issue by jamskahler** [facebookincubator/oculus-go-kernel#1]
So I guess the question is this. Does this kernel *actually* work? I would like to be able to test it out, but am afraid that if I load it onto the device, that I won't be able to factory reset my device as a way out.

Please advise

**Comment by visigoth** [comment]
@jamskahler the kernel published here is indeed our kernel. however, our device utilizes secure boot, so only a kernel signed by Oculus will boot on retail devices.

**Comment by cleoag** [comment]
any way it can help fix bricked oculus go devices after factory reset?

**Comment by intervigilium** [comment]
No, see the answer provided by visigoth above.

**Comment by kungfooman** [comment]
It feels iffy that a company wants to decide what I am allowed to do with "my" devices... and then even using GPL is the cherry on top of the iffyness.
